# Generated by Django 4.2.13 on 2024-06-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=50)),
                ('idEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_proyecto', to='Certamen2.usuario')),
                ('idProfesor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_proyecto', to='Certamen2.usuario')),
            ],
        ),
    ]
