# Generated by Django 4.2.13 on 2024-06-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certamen2', '0003_usuario_email_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('0', 'Estudiante'), ('1', 'Profesor')], max_length=50),
        ),
    ]
