# Generated by Django 4.2.13 on 2024-06-01 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Certamen2', '0004_alter_usuario_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='idProfesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_proyecto', to='Certamen2.usuario'),
        ),
    ]
