# Generated by Django 4.2.13 on 2024-06-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Certamen2', '0005_alter_proyecto_idprofesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='idEstudiante',
            new_name='Estudiante',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='idProfesor',
            new_name='Profesor',
        ),
    ]
