# Generated by Django 4.2.13 on 2024-06-01 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Certamen2', '0006_rename_idestudiante_proyecto_estudiante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='Estudiante',
            new_name='estudiante',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='Profesor',
            new_name='profesor',
        ),
    ]
